In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/67-new/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
acc_test = []

for d in dirs:
    acc_one = []
    for i in d:
        try:
            j = json.load(open(i + '/acc.json'))
            acc_one.append(j['test'])
        except:
            acc_one.append(np.nan)
    acc_test.append(acc_one)
    
acc_test = np.array(acc_test)

In [6]:
np.nanmean(acc_test, axis=1)

array([0.8088, 0.7083, 0.7916])

In [7]:
np.nanstd(acc_test, axis=1)

array([0.01332516, 0.00928493, 0.00836899])

In [8]:
acc_test

array([[0.802, 0.791, 0.811, 0.806, 0.801, 0.794, 0.825, 0.838, 0.809,
        0.811],
       [0.703, 0.706, 0.711, 0.712, 0.718, 0.712, 0.683, 0.714, 0.712,
        0.712],
       [0.788, 0.789, 0.788, 0.778, 0.79 , 0.796, 0.804, 0.786, 0.808,
        0.789]])