In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/86/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
accs = [[json.load(open(i + '/acc.json')) for i in d] for d in dirs]

In [6]:
acc_test = np.array([[i['test'] for i in a] for a in accs])

In [7]:
acc_test.mean(axis=1)

array([0.8002, 0.8091, 0.7982, 0.7854, 0.7605])

In [8]:
acc_test.std(axis=1)

array([0.00835225, 0.00874586, 0.01256821, 0.00905759, 0.02507688])

In [9]:
acc_test

array([[0.801, 0.802, 0.801, 0.795, 0.78 , 0.815, 0.806, 0.802, 0.799,
        0.801],
       [0.821, 0.804, 0.813, 0.819, 0.809, 0.794, 0.795, 0.808, 0.812,
        0.816],
       [0.785, 0.794, 0.805, 0.794, 0.804, 0.793, 0.812, 0.792, 0.824,
        0.779],
       [0.781, 0.793, 0.791, 0.793, 0.78 , 0.785, 0.771, 0.803, 0.781,
        0.776],
       [0.759, 0.738, 0.786, 0.707, 0.747, 0.779, 0.787, 0.782, 0.777,
        0.743]])