In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/87/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
accs = [[json.load(open(i + '/acc.json')) for i in d] for d in dirs]

In [6]:
acc_test = np.array([[i['test'] for i in a] for a in accs])

In [7]:
acc_test.mean(axis=1)

array([0.7936, 0.7912, 0.7908, 0.7849, 0.7799])

In [8]:
acc_test.std(axis=1)

array([0.00135647, 0.003995  , 0.00386782, 0.00755579, 0.0069347 ])

In [9]:
acc_test

array([[0.792, 0.794, 0.791, 0.794, 0.795, 0.794, 0.793, 0.793, 0.796,
        0.794],
       [0.789, 0.784, 0.789, 0.787, 0.79 , 0.797, 0.796, 0.794, 0.791,
        0.795],
       [0.791, 0.795, 0.786, 0.8  , 0.792, 0.788, 0.79 , 0.789, 0.789,
        0.788],
       [0.779, 0.78 , 0.777, 0.786, 0.785, 0.78 , 0.789, 0.805, 0.785,
        0.783],
       [0.785, 0.788, 0.776, 0.783, 0.789, 0.778, 0.766, 0.782, 0.781,
        0.771]])