In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/50-new/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
accs = [[json.load(open(i + '/acc.json')) for i in d] for d in dirs]

In [6]:
acc_test = np.array([[i['test'] for i in a] for a in accs])

In [7]:
acc_test.mean(axis=1)

array([0.7036, 0.802 , 0.8042, 0.7075, 0.7901])

In [8]:
acc_test.std(axis=1)

array([0.00628013, 0.01116244, 0.00843564, 0.0076974 , 0.00548544])

In [9]:
acc_test

array([[0.705, 0.708, 0.71 , 0.702, 0.712, 0.704, 0.704, 0.689, 0.705,
        0.697],
       [0.795, 0.799, 0.786, 0.819, 0.819, 0.811, 0.794, 0.794, 0.81 ,
        0.793],
       [0.798, 0.804, 0.799, 0.803, 0.802, 0.793, 0.82 , 0.802, 0.82 ,
        0.801],
       [0.714, 0.704, 0.705, 0.708, 0.692, 0.7  , 0.717, 0.717, 0.714,
        0.704],
       [0.784, 0.786, 0.792, 0.798, 0.783, 0.793, 0.797, 0.79 , 0.795,
        0.783]])