In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/88/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
accs = [[json.load(open(i + '/acc.json')) for i in d] for d in dirs]

In [6]:
acc_test = np.array([[i['test'] for i in a] for a in accs])

In [7]:
acc_test.mean(axis=1)

array([0.79177778, 0.79788889, 0.79877778, 0.78677778, 0.75366667])

In [8]:
acc_test.std(axis=1)

array([0.01337309, 0.01343664, 0.00842981, 0.01700182, 0.02021551])

In [9]:
acc_test

array([[0.815, 0.801, 0.801, 0.78 , 0.782, 0.78 , 0.771, 0.795, 0.801],
       [0.813, 0.805, 0.795, 0.805, 0.806, 0.8  , 0.765, 0.804, 0.788],
       [0.795, 0.8  , 0.793, 0.782, 0.807, 0.814, 0.801, 0.8  , 0.797],
       [0.78 , 0.793, 0.779, 0.773, 0.759, 0.811, 0.813, 0.776, 0.797],
       [0.784, 0.745, 0.726, 0.745, 0.762, 0.73 , 0.748, 0.755, 0.788]])