In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/88/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [5]:
accs = [[json.load(open(i + '/acc.json')) for i in d] for d in dirs]

In [6]:
acc_test = np.array([[i['test'] for i in a] for a in accs])

In [7]:
acc_test.mean(axis=1)

array([0.7929, 0.7936, 0.7933, 0.7915, 0.7864])

In [8]:
acc_test.std(axis=1)

array([0.00526213, 0.00257682, 0.0029    , 0.00620081, 0.0072    ])

In [9]:
acc_test

array([[0.792, 0.795, 0.796, 0.797, 0.792, 0.795, 0.797, 0.778, 0.793,
        0.794],
       [0.793, 0.798, 0.794, 0.796, 0.794, 0.791, 0.791, 0.789, 0.796,
        0.794],
       [0.796, 0.794, 0.793, 0.788, 0.793, 0.792, 0.791, 0.798, 0.797,
        0.791],
       [0.797, 0.784, 0.78 , 0.786, 0.798, 0.798, 0.793, 0.788, 0.797,
        0.794],
       [0.79 , 0.786, 0.792, 0.792, 0.791, 0.785, 0.778, 0.772, 0.781,
        0.797]])