In [1]:
jobs = # list of lists of strings for job IDs.

In [2]:
RESULT_DIR = 'results/64-new/'

In [3]:
import glob
import numpy as np
import pandas as pd
import json
%matplotlib inline
from matplotlib import pyplot as plt

In [4]:
dirs = [[glob.glob(f'results/{i}-*/[0-9]*')[0] for i in j] for j in jobs]

In [8]:
acc_test = []

for d in dirs:
    acc_one = []
    for i in d:
        try:
            j = json.load(open(i + '/acc.json'))
            acc_one.append(j['test'])
        except:
            acc_one.append(np.nan)
    acc_test.append(acc_one)
    
acc_test = np.array(acc_test)

In [9]:
np.nanmean(acc_test, axis=1)

/home/delta/.pyenv/versions/anaconda3-4.3.0/envs/anaconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice
  """Entry point for launching an IPython kernel.


array([0.8233, 0.7089,    nan])

In [10]:
np.nanstd(acc_test, axis=1)

/home/delta/.pyenv/versions/anaconda3-4.3.0/envs/anaconda/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1667: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)


array([0.01067755, 0.0104733 ,        nan])

In [11]:
acc_test

array([[0.826, 0.838, 0.802, 0.811, 0.825, 0.832, 0.827, 0.836, 0.817,
        0.819],
       [0.699, 0.733, 0.7  , 0.711, 0.71 , 0.704, 0.705, 0.711, 0.72 ,
        0.696],
       [  nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,
          nan]])